#!/bin/bash
if [ $# -eq 0 ]; then
  echo "Usage: $0 create|update <DNSDOMAIN> <ORIGIN_ACCESS_IDENTITY>"
  echo "e.g. $0 create example.com OSKIVNROENOEM"
  exit 1
else
  export AWS_DEFAULT_PROFILE=aws-s3-website
  STACK_NAME=`echo $2 | sed -e 's/\./\-/g'`
  # Configures the aws-cli, requires an access key id and secret
  aws configure --profile $AWS_DEFAULT_PROFILE
  # Creates a CloudFormation stack for the s3 bucket website
  if [ $1 == "update" ]; then
    COMMAND=update-stack
  else
    COMMAND=create-stack
  fi
  aws cloudformation $COMMAND \
    --stack-name www-$STACK_NAME \
    --template-body file://template.json \
    --capabilities CAPABILITY_IAM \
    --parameters ParameterKey=DomainName,ParameterValue=$2 ParameterKey=OriginAccessIdentity,ParameterValue=$3
fi
