#!/bin/bash
if [ $# -eq 0 ]; then
  echo "Usage: $0 <DOMAIN_NAME> <ORIGIN_ACCESS_IDENTIY>"
  echo "e.g. $0 example.com E115G30W0SLMRZ"
  exit 1
else
  export AWS_DEFAULT_PROFILE=aws-s3-website
  STACK_NAME=`echo $1 | sed -e 's/\./\-/g'`
  # Configures the aws-cli, requires an access key id and secret
  aws configure --profile $AWS_DEFAULT_PROFILE
  # Creates a CloudFormation stack for the s3 bucket website
  #aws cloudformation update-stack \
  aws cloudformation create-stack \
    --stack-name www-$STACK_NAME \
    --template-body file://template.json \
    --capabilities CAPABILITY_IAM \
    --parameters ParameterKey=DomainName,ParameterValue=$1 ParameterKey=OriginAccessIdentity,ParameterValue=$2
fi
